version: '3.8'

services:
  app:
    build:
      context: .
      target: backend
    container_name: SS_BE_DEV
    ports:
      - "8002:8001"
      - "8081:8080"
    volumes:
      - ./docker/env/.env.dev:/var/www/.env
