name: Cerita nya ini CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Copy secret env
        run: copy C:\Users\SMAKA-SERVER\ppdb\seragam-app-v2\docker\env\.env.prod C:\Users\SMAKA-SERVER\ppdb\actions-runner-ss\_work\seragam-app-v2\seragam-app-v2\docker\env\.env.prod

      - uses: actions/checkout@v3
      - name: Pull and build Docker
        run: |
          git pull
          docker-compose up -d --build
