name: Cerita nya ini CI/CD DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ss-dev
    steps:
      - uses: actions/checkout@v3
      - name: Pull and build Docker
        env:
          APP_ENV: development
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cp C:\Users\SMAKA-SERVER\ppdb\seragam-app-v2\docker\env\.env.dev C:\Users\SMAKA-SERVER\ppdb\actions-runner-ss-dev\_work\seragam-app-v2\seragam-app-v2\docker\env\.env.dev
          cp C:\Users\SMAKA-SERVER\ppdb\seragam-app-v2\docker\env\.env.db C:\Users\SMAKA-SERVER\ppdb\actions-runner-ss-dev\_work\seragam-app-v2\seragam-app-v2\docker\env\.env.db
          cp C:\Users\SMAKA-SERVER\ppdb\seragam-app-v2\docker\env\.env.prod C:\Users\SMAKA-SERVER\ppdb\actions-runner-ss-dev\_work\seragam-app-v2\seragam-app-v2\docker\env\.env.prod
          ls
          git pull
          docker-compose -f docker-compose.dev.yaml -p seragam-app-v2-dev up -d --build
