name: Cerita nya ini CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ss-prod
    steps:
      - uses: actions/checkout@v3
      - name: Pull and build Docker
        run: |
          cp C:\Users\SMAKA-SERVER\ppdb\seragam-app-v2\docker\env\.env.prod C:\Users\SMAKA-SERVER\ppdb\actions-runner-ss\_work\seragam-app-v2\seragam-app-v2\docker\env\.env.prod
          cp C:\Users\SMAKA-SERVER\ppdb\seragam-app-v2\docker\env\.env.db C:\Users\SMAKA-SERVER\ppdb\actions-runner-ss\_work\seragam-app-v2\seragam-app-v2\docker\env\.env.db
          ls
          git pull
          docker-compose up -d --build
